#############################################################################
# Makefile for building: test_game.app/Contents/MacOS/test_game
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  test_game.pro
# Template: app
# Command: /Users/bradley101/Qt5.2.1/5.2.1/ios/bin/qmake -spec macx-ios-clang CONFIG+=x86 CONFIG+=iphonesimulator CONFIG+=declarative_debug CONFIG+=qml_debug -spec macx-xcode -o test_game.xcodeproj/project.pbxproj test_game.pro
#############################################################################

MAKEFILE      = project.pbxproj

MOC       = /Users/bradley101/Qt5.2.1/5.2.1/ios/bin/moc
UIC       = /Users/bradley101/Qt5.2.1/5.2.1/ios/bin/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DDARWIN_NO_CARBON -DQT_NO_PRINTER -DQT_NO_PRINTDIALOG -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH       = -I../../../Qt5.2.1/5.2.1/ios/mkspecs/macx-ios-clang -I. -I/Users/bradley101/Qt5.2.1/5.2.1/ios/mkspecs/macx-ios-clang/ios -I../engine -I../../../Qt5.2.1/5.2.1/ios/include -I../../../Qt5.2.1/5.2.1/ios/include/QtOpenGL -I../../../Qt5.2.1/5.2.1/ios/include/QtWidgets -I../../../Qt5.2.1/5.2.1/ios/include/QtGui -I../../../Qt5.2.1/5.2.1/ios/include/QtCore -I.
DEL_FILE  = rm -f
MOVE      = mv -f

IMAGES = 
PARSERS =
preprocess: $(PARSERS) compilers
clean preprocess_clean: parser_clean compiler_clean

parser_clean:
mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compilers: ./qrc_assets.cpp
compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_assets.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_assets.cpp
qrc_assets.cpp: assets.qrc \
		fenrir.png
	/Users/bradley101/Qt5.2.1/5.2.1/ios/bin/rcc -name assets assets.qrc -o qrc_assets.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean 

